version: '3'
services:
  strapi:
    container_name: strapi
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - '1337:1337'
    volumes:
      - ./backend:/opt/app
      - /opt/app/node_modules

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - strapi
