[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/admin"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[nixpacks]
node-version = "18"
