services:
  - type: web
    name: strapi-backend
    env: node
    plan: starter
    buildCommand: cp -r backend/* . && npm install && npm run build
    startCommand: npm start
    healthCheckPath: /admin
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: sqlite
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
